# Messages Monitoring Model

## Phase 1: Preprocessing the Data

### Load in the Required Libraries

In [4]:
# for dealing with data
import pandas as pd
import numpy as np
from datasets import load_dataset

# for data visualizations
import matplotlib.pyplot as plt
import seaborn as sns

# for processing data
from sklearn.model_selection import train_test_split

# for evaluation metrics
from sklearn.metrics import accuracy_score

### Load in the Datasets

In [5]:
# download the kaggle datasets
!kaggle datasets download -d uciml/sms-spam-collection-dataset
!kaggle datasets download -d team-ai/spam-text-message-classification
!unzip sms-spam-collection-dataset.zip
!unzip spam-text-message-classification.zip
!rm sms-spam-collection-dataset.zip
!rm spam-text-message-classification.zip

Downloading sms-spam-collection-dataset.zip to /Users/necro_kudo/Developer/misk-dsi/capstone-project
100%|█████████████████████████████████████████| 211k/211k [00:00<00:00, 680kB/s]
100%|█████████████████████████████████████████| 211k/211k [00:00<00:00, 678kB/s]
Downloading spam-text-message-classification.zip to /Users/necro_kudo/Developer/misk-dsi/capstone-project
100%|█████████████████████████████████████████| 208k/208k [00:00<00:00, 472kB/s]
100%|█████████████████████████████████████████| 208k/208k [00:00<00:00, 471kB/s]
Archive:  sms-spam-collection-dataset.zip
  inflating: spam.csv
Archive:  spam-text-message-classification.zip
  inflating: SPAM text message 20170820 - Data.csv

In [9]:
# read in the datasets

sms_data1 = pd.read_csv("SPAM text message 20170820 - Data.csv")
sms_data2 = pd.read_csv("spam.csv", encoding='latin-1')
sms_data3 = pd.DataFrame((load_dataset("sms_spam")['train']))

Reusing dataset sms_spam (/Users/necro_kudo/.cache/huggingface/datasets/sms_spam/plain_text/1.0.0/53f051d3b5f62d99d61792c91acefe4f1577ad3e4c216fb0ad39e30b9f20019c)
100%|██████████| 1/1 [00:00<00:00, 320.52it/s]

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [24]:
# unify the features names
sms_data1.rename({"Category": "label", "Message": "message"}, axis=1)

# unify the features names & drop unwanted features
sms_data2.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)
sms_data2.rename({"v1" : "label", "v2" : "message"}, axis=1)

# unify the features names
sms_data3.rename({"sms" : "message"})

                                                    sms  label
0     Go until jurong point, crazy.. Available only ...      0
1                       Ok lar... Joking wif u oni...\n      0
2     Free entry in 2 a wkly comp to win FA Cup fina...      1
3     U dun say so early hor... U c already then say...      0
4     Nah I don't think he goes to usf, he lives aro...      0
...                                                 ...    ...
5569  This is the 2nd time we have tried 2 contact u...      1
5570             Will ü b going to esplanade fr home?\n      0
5571  Pity, * was in mood for that. So...any other s...      0
5572  The guy did some bitching but I acted like i'd...      0
5573                       Rofl. Its true to its name\n      0

[5574 rows x 2 columns]